# Generated by Django 4.1.6 on 2023-05-02 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(max_length=255, upload_to="agency/properties"),
                ),
                (
                    "property",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agency.property",
                    ),
                ),
            ],
            options={
                "verbose_name": "property gallery",
                "verbose_name_plural": "property gallery",
            },
        ),
    ]
