# Generated by Django 4.1.6 on 2023-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="maps_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="property",
            name="video360_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="property",
            name="videoblog_url",
            field=models.URLField(default=""),
        ),
    ]
