# Generated by Django 4.1.6 on 2023-02-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_property_maps_url_alter_property_video360_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="maps_url",
            field=models.URLField(default="https://www.google.com/maps/?hl=es"),
        ),
        migrations.AlterField(
            model_name="property",
            name="video360_url",
            field=models.URLField(default="https://www.youtube.com/?hl=es&gl=EC"),
        ),
        migrations.AlterField(
            model_name="property",
            name="videoblog_url",
            field=models.URLField(default="https://www.youtube.com/?hl=es&gl=EC"),
        ),
    ]
