# Generated by Django 4.1.6 on 2023-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0002_alter_property_property_name_alter_property_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="property_name",
            field=models.CharField(max_length=200),
        ),
    ]
