# Generated by Django 4.1.6 on 2023-02-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0003_alter_property_property_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="maps_url",
            field=models.URLField(
                default="https://www.google.com/maps/?hl=es", max_length=400
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="video360_url",
            field=models.URLField(
                default="https://www.youtube.com/?hl=es&gl=EC", max_length=400
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="videoblog_url",
            field=models.URLField(
                default="https://www.youtube.com/?hl=es&gl=EC", max_length=400
            ),
        ),
    ]
