# Generated by Django 4.1.6 on 2023-02-10 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0004_property_owner_property_owner_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="property",
            options={"verbose_name": "property", "verbose_name_plural": "properties"},
        ),
    ]
